// TraceRenderer.swift — owns the identity-to-handle map and the per-element
// draw loop. This is where the spec's three identity invariants are enforced:
//
//   1. Hit-testing routes to Rust (VexelFile.hitTest), never to Skia. The
//      renderer holds the geometry only for drawing.
//   2. Each interactive element gets its own `canvas.drawPath` call. The only
//      SkPicture batching allowed is for `flags.is_decorative == true` shapes.
//   3. The `handles` map below IS the identity-to-handle map. It lives in
//      Swift, not inside Skia. Highlights, animations, and per-element re-style
//      operations touch only the relevant handle and trigger redraw.

import Foundation
import SkiaKit
import UIKit

final class TraceRenderer {
    struct ElementHandle {
        let id: String?
        let path: SkPath
        var paint: SkPaint
        var strokePaint: SkPaint?
        var strokeProgress: Float = 1.0  // 0..1 — drives stroke-draw anim
        var fillOpacity: Float = 1.0     // 0..1 — drives fill-fade anim
        let isDecorative: Bool
        let bbox: CGRect
    }

    /// element_index → handle. The key is the GEOM index from the .vex file.
    private(set) var handles: [Int: ElementHandle] = [:]
    private(set) var elementOrder: [Int] = []

    /// Optional cached picture of decorative shapes. Rebuilt only when the file
    /// is reloaded; never invalidated by animation or highlight changes.
    private var decorativePicture: SkPicture?

    weak var owner: VexelView?

    func load(from file: VexelFile) throws {
        handles.removeAll(keepingCapacity: true)
        elementOrder.removeAll(keepingCapacity: true)
        decorativePicture = nil

        // Iterate elements in document (GEOM) order. UniFFI exposes
        // `each_element` returning a sequence of ElementSummary structs with
        // the verb stream and points already materialized.
        let elements = try file.inner.elements()  // generated by UniFFI
        var decorativeRecorder: SkPictureRecorder? = nil

        for (idx, el) in elements.enumerated() {
            let path = PathConvert.buildPath(verbs: el.verbs, points: el.points)
            var paint = SkPaint()
            paint.isAntiAlias = true
            if el.fillRgba != 0 {
                paint.color = SkColor(packed: el.fillRgba)
                paint.style = .fill
                paint.fillRule = el.flags.evenOdd ? .evenOdd : .winding
            } else {
                paint.style = .stroke
            }

            var strokePaint: SkPaint? = nil
            if el.strokeRgba != 0 && el.strokeWidth > 0 {
                var sp = SkPaint()
                sp.isAntiAlias = true
                sp.color = SkColor(packed: el.strokeRgba)
                sp.style = .stroke
                sp.strokeWidth = CGFloat(el.strokeWidth)
                sp.strokeCap = el.flags.linecapRound ? .round : .butt
                sp.strokeJoin = el.flags.linejoinRound ? .round : .miter
                strokePaint = sp
            }

            let bbox = CGRect(
                x: CGFloat(el.bboxMinX), y: CGFloat(el.bboxMinY),
                width: CGFloat(el.bboxMaxX - el.bboxMinX),
                height: CGFloat(el.bboxMaxY - el.bboxMinY)
            )
            let handle = ElementHandle(
                id: el.id, path: path, paint: paint,
                strokePaint: strokePaint, isDecorative: el.flags.isDecorative,
                bbox: bbox
            )
            handles[idx] = handle
            elementOrder.append(idx)

            // Decorative shapes go into the cached picture; interactive ones
            // are drawn live per-frame so animations and highlights work.
            if el.flags.isDecorative {
                if decorativeRecorder == nil {
                    let bounds = SkRect(viewBox: file.viewBox)
                    decorativeRecorder = SkPictureRecorder()
                    _ = decorativeRecorder!.beginRecording(bounds)
                }
                let canvas = decorativeRecorder!.recordingCanvas
                canvas.drawPath(path, with: paint)
                if let sp = strokePaint { canvas.drawPath(path, with: sp) }
            }
        }
        if let rec = decorativeRecorder {
            decorativePicture = rec.endRecording()
        }
    }

    func draw(on canvas: SkCanvas, highlighted: Set<String>, highlightColor: UIColor, boost: CGFloat) {
        if let pic = decorativePicture {
            canvas.draw(picture: pic)
        }
        for idx in elementOrder {
            guard let h = handles[idx], !h.isDecorative else { continue }
            // Fill (respecting animated opacity).
            var fillPaint = h.paint
            fillPaint.alpha = UInt8((Float(fillPaint.alpha) * h.fillOpacity).rounded())
            canvas.drawPath(h.path, with: fillPaint)
            // Stroke (respecting strokeProgress as a leading dash effect).
            if var sp = h.strokePaint {
                if h.strokeProgress < 1.0 {
                    sp.pathEffect = SkPathEffect.trim(start: 0, end: h.strokeProgress)
                }
                canvas.drawPath(h.path, with: sp)
            }
            // Highlight as an overlay — doesn't mutate base paint, preserving
            // the identity-to-handle invariant.
            if let id = h.id, highlighted.contains(id) {
                var hp = SkPaint()
                hp.isAntiAlias = true
                hp.color = SkColor(uiColor: highlightColor)
                hp.style = .stroke
                hp.strokeWidth = max(CGFloat(h.strokePaint?.strokeWidth ?? 1.0) * boost, 2.0)
                canvas.drawPath(h.path, with: hp)
            }
        }
    }

    func setStrokeProgress(_ p: Float, forElement idx: Int) {
        guard var h = handles[idx] else { return }
        h.strokeProgress = max(0, min(1, p))
        handles[idx] = h
        owner?.requestRedraw()
    }

    func setFillOpacity(_ a: Float, forElement idx: Int) {
        guard var h = handles[idx] else { return }
        h.fillOpacity = max(0, min(1, a))
        handles[idx] = h
        owner?.requestRedraw()
    }
}
