// MermaidRealScreen — verifies Vexel renders real Mermaid 10.9.x output.
//
// Each fixture below was generated by @mermaid-js/mermaid-cli@10.9.1 with
// htmlLabels:false and the same themeVariables Curo uses. These are the
// EXACT patterns that hit Vexel in production:
//   - <style> blocks with #diagram-prefixed selectors
//   - <g transform="translate(...)"> per node
//   - native <text>/<tspan> labels
//   - mid-cascade !important rules
//
// Toggle "stream" to verify stroke-by-stroke reveal still works on each.

import React, { useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Switch, Text, View } from 'react-native';
import { VexelView } from '../vexel-runtime';
import {
  CLASS,
  FLOWCHART_COMPLEX,
  FLOWCHART_SIMPLE,
  SEQUENCE,
  STATE,
} from '../fixtures/realMermaid';

type Fixture =
  | 'flowchart-simple'
  | 'flowchart-complex'
  | 'sequence'
  | 'class'
  | 'state';

const SOURCES: Record<Fixture, string> = {
  'flowchart-simple': FLOWCHART_SIMPLE,
  'flowchart-complex': FLOWCHART_COMPLEX,
  sequence: SEQUENCE,
  class: CLASS,
  state: STATE,
};

const FIXTURES: Fixture[] = [
  'flowchart-simple',
  'flowchart-complex',
  'sequence',
  'class',
  'state',
];

export function MermaidRealScreen() {
  const [active, setActive] = useState<Fixture>('flowchart-simple');
  const [stream, setStream] = useState(false);
  const [streamKey, setStreamKey] = useState(0);

  const source = SOURCES[active];

  return (
    <ScrollView contentContainerStyle={s.scroll}>
      <Text style={s.h2}>Real Mermaid (10.9.x)</Text>
      <Text style={s.p}>
        Five SVGs straight from @mermaid-js/mermaid-cli — flowchart, sequence,
        class, state — rendered without any pre-processing. These are the
        exact patterns Curo's lecture agent produces. Tests v0.0.4 fixes:
        {'\n'}• <Text style={s.mono}>{'<svg id="diagram">'}</Text> in the
        ancestor stack so <Text style={s.mono}>#diagram .node rect</Text>
        matches{'\n'}• <Text style={s.mono}>{'<g transform="...">'}</Text>{' '}
        forwarded to RN-SVG <Text style={s.mono}>{'<G>'}</Text>{' '}
        so nodes don't pile up at (0,0)
      </Text>

      <View style={s.row}>
        {FIXTURES.map((f) => (
          <Pressable
            key={f}
            onPress={() => setActive(f)}
            style={[s.chip, active === f && s.chipActive]}
          >
            <Text style={[s.chipText, active === f && s.chipTextActive]}>{f}</Text>
          </Pressable>
        ))}
      </View>

      <View style={s.streamRow}>
        <Text style={s.streamLabel}>streamReveal</Text>
        <Switch
          value={stream}
          onValueChange={(v) => {
            setStream(v);
            setStreamKey((k) => k + 1);
          }}
        />
        {stream ? (
          <Pressable onPress={() => setStreamKey((k) => k + 1)} style={s.replay}>
            <Text style={s.replayText}>replay</Text>
          </Pressable>
        ) : null}
      </View>

      <View style={s.canvas}>
        <VexelView
          key={`${active}-${streamKey}`}
          source={source}
          fit="contain"
          padding={16}
          highlight="none"
          streamReveal={stream}
          streamElementMs={400}
          streamPauseMs={60}
          streamEasing="hand-natural"
          onCSSWarning={(w) => console.warn('[Vexel CSS]', w.kind, w.message)}
          onLoad={(g) =>
            console.log(`[${active}] shapes=${g.shapes.size} viewBox=${g.viewBox}`)
          }
          onError={(e) => console.error(`[${active}] error`, e.kind, e.message)}
          style={{ flex: 1 }}
        />
      </View>

      <Text style={s.note}>
        Source: {source.length.toLocaleString()} chars · viewBox extracted at render
      </Text>
    </ScrollView>
  );
}

const s = StyleSheet.create({
  scroll: { padding: 16, gap: 12, paddingBottom: 32 },
  h2: { fontSize: 20, fontWeight: '700', color: '#0f172a' },
  p: { fontSize: 12, color: '#475569', lineHeight: 18 },
  mono: { fontFamily: 'Menlo', fontSize: 11 },
  row: { flexDirection: 'row', gap: 6, flexWrap: 'wrap' },
  chip: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 14,
    backgroundColor: '#e2e8f0',
  },
  chipActive: { backgroundColor: '#0f172a' },
  chipText: { color: '#0f172a', fontSize: 11, fontWeight: '600' },
  chipTextActive: { color: '#f8fafc' },
  streamRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  streamLabel: { fontSize: 12, color: '#0f172a', fontWeight: '600' },
  replay: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 12,
    backgroundColor: '#0f172a',
  },
  replayText: { color: '#f8fafc', fontSize: 11, fontWeight: '600' },
  canvas: {
    height: 380,
    borderRadius: 12,
    backgroundColor: '#f8fafc',
    overflow: 'hidden',
  },
  note: { fontSize: 11, color: '#64748b', fontStyle: 'italic' },
});
